### **Overview**

Dear Learner, 

Congratulations, you have studied NumPy all the way through the end of this bootcamp!!! This is the final graded hands-on exercise where you will be accomplishing the below mentioned task.

**Author:** Avantika Podar

###Task 1:   

Construct a random 3x28x28 NumPy array called *original* to represent an image and then convert this into into a 1x(3x28x28) array called *flat*. This converts it into a single row of pixels. Next, convert this to a 1D array (flatten the array using flat.flatten()). Print shape of all arrays. You may use the random function to generate the array.



In [2]:
import numpy as np
original = np.random.rand(3,28,28); original

array([[[0.38690816, 0.52102601, 0.75270609, ..., 0.32832636,
         0.99816758, 0.88134795],
        [0.52343694, 0.91384093, 0.63927776, ..., 0.62058792,
         0.7755078 , 0.82403864],
        [0.07447864, 0.9775395 , 0.46021467, ..., 0.00953656,
         0.26401203, 0.63275502],
        ...,
        [0.42424558, 0.9024205 , 0.21242824, ..., 0.18745464,
         0.18324604, 0.75049022],
        [0.86952359, 0.93155959, 0.52922351, ..., 0.47640473,
         0.01413956, 0.24458737],
        [0.62194729, 0.13898941, 0.809992  , ..., 0.86780583,
         0.80530226, 0.49657228]],

       [[0.68577223, 0.64661121, 0.37199115, ..., 0.26720807,
         0.58874953, 0.65628952],
        [0.6082064 , 0.64492641, 0.77063602, ..., 0.41648131,
         0.54694663, 0.86162723],
        [0.96538572, 0.45081472, 0.83969725, ..., 0.67502028,
         0.79170724, 0.04690211],
        ...,
        [0.17941315, 0.65731578, 0.08861302, ..., 0.06753702,
         0.68054046, 0.85547313],
        [0.0

In [3]:
original.shape

(3, 28, 28)

In [4]:
flat = original.reshape(1, -1); flat

array([[0.38690816, 0.52102601, 0.75270609, ..., 0.76476873, 0.40084417,
        0.0698159 ]])

In [5]:
flat.shape

(1, 2352)

In [6]:
last = flat.flatten(); last

array([0.38690816, 0.52102601, 0.75270609, ..., 0.76476873, 0.40084417,
       0.0698159 ])

In [7]:
last.shape

(2352,)

### Task 2: Print out the following: 
  * dimension of the arrays.
  * memory address of the arrays (pointer).
  * shape of the arrays.
  * data types of the arrays. 




In [8]:
original.ndim, id(original), original.shape, original.dtype

(3, 139957277635168, (3, 28, 28), dtype('float64'))

In [9]:
flat.ndim, id(flat), flat.shape, flat.dtype

(2, 139957277860848, (1, 2352), dtype('float64'))

In [10]:
last.ndim, id(last), last.shape, last.dtype

(1, 139957277443936, (2352,), dtype('float64'))

### Task 3: 
Construct a new array which is a negative of the *original* array, i.e, all elements are negative of those in the *original* array. Print the new array. Add the original and new arrays. Print the result. 

In [11]:
new = np.negative(original); new

array([[[-0.38690816, -0.52102601, -0.75270609, ..., -0.32832636,
         -0.99816758, -0.88134795],
        [-0.52343694, -0.91384093, -0.63927776, ..., -0.62058792,
         -0.7755078 , -0.82403864],
        [-0.07447864, -0.9775395 , -0.46021467, ..., -0.00953656,
         -0.26401203, -0.63275502],
        ...,
        [-0.42424558, -0.9024205 , -0.21242824, ..., -0.18745464,
         -0.18324604, -0.75049022],
        [-0.86952359, -0.93155959, -0.52922351, ..., -0.47640473,
         -0.01413956, -0.24458737],
        [-0.62194729, -0.13898941, -0.809992  , ..., -0.86780583,
         -0.80530226, -0.49657228]],

       [[-0.68577223, -0.64661121, -0.37199115, ..., -0.26720807,
         -0.58874953, -0.65628952],
        [-0.6082064 , -0.64492641, -0.77063602, ..., -0.41648131,
         -0.54694663, -0.86162723],
        [-0.96538572, -0.45081472, -0.83969725, ..., -0.67502028,
         -0.79170724, -0.04690211],
        ...,
        [-0.17941315, -0.65731578, -0.08861302, ..., -

In [12]:
result = new + original; result

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

###Task 4

A 3x28x28 basically means 28x28 matrices repeated three times. How would you access the first 10 elements of the 2nd row of the second 28x28 matrix? Consider the original array for this. Print the elements.

In [13]:
original[1][1][0:10]

array([0.6082064 , 0.64492641, 0.77063602, 0.61453607, 0.35672535,
       0.10831409, 0.15265777, 0.83113831, 0.51675103, 0.86148265])

### Task 5 
A 3x28x28 image means 3 channels of Red, Green, or Blue (Popularly known as RGB image). Each color channel has a height and width, which is 28X28 in this case. The entire picture can represented through this method. Print the shape of the Blue pixel matrix and its first 3 rows.

In [14]:
blue_pixel = original[2][0:3]; blue_pixel

array([[0.95211769, 0.87724023, 0.36223329, 0.18414018, 0.34253711,
        0.82520548, 0.95690394, 0.06880063, 0.61608563, 0.95395618,
        0.15430422, 0.00573282, 0.82259441, 0.49707949, 0.96022128,
        0.16671064, 0.03549137, 0.55818783, 0.47880282, 0.94638251,
        0.2650488 , 0.38768649, 0.38593953, 0.93317984, 0.34052562,
        0.63476905, 0.8680736 , 0.60453566],
       [0.46559101, 0.62792978, 0.31920574, 0.78344447, 0.34326428,
        0.44863363, 0.22280612, 0.9349881 , 0.45155546, 0.32084133,
        0.23833858, 0.18125256, 0.54585863, 0.49377885, 0.02876223,
        0.58129604, 0.54991916, 0.04912887, 0.63735809, 0.57482468,
        0.6182116 , 0.28042158, 0.21654058, 0.58151842, 0.32302447,
        0.77408389, 0.5937274 , 0.25034028],
       [0.62562788, 0.88936278, 0.91811829, 0.27336416, 0.60711309,
        0.1907847 , 0.41266404, 0.23741522, 0.97697474, 0.09549938,
        0.67026179, 0.60668461, 0.05048031, 0.03212332, 0.30171944,
        0.61913856, 0.5920

In [15]:
blue_pixel.shape

(3, 28)

### Task 6 
Create a 1 dimensional numpy array of the first 50 even numbers. Convert this to a 10x5 numpy array and print its transpose. 

In [16]:
even = np.arange(2,102,2); even

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [17]:
new_even = even.reshape(10,5); new_even

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [18]:
trans_even = new_even.transpose(); trans_even

array([[  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

###Task 7 
Consider the 10x5 array created in Task 6. Find the mean of each row and column. You may use in built functions or write your own code.

In [19]:
new_even.sum(axis = 0)/10 #column mean

array([47., 49., 51., 53., 55.])

In [20]:
new_even.sum(axis=1)/5 #row mean

array([ 6., 16., 26., 36., 46., 56., 66., 76., 86., 96.])

### Task 8
Can we create a 3x3 array of the first 50 even numbers? Why or why not? What are other values of m and n for which mxn dimension is allowed for 50 elements?

In [21]:
even = np.arange(2,102,2); even

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [28]:
a = even.reshape(-1); a

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [29]:
a.shape

(50,)

A 3x3 array of size 50 is impossible because 3  or 9 are not factors of 50. 

The other values of m and n for which mXn dimension is allowed are: 

1. 1x50 
2. 2x25 
3. 5x10
4. 10x5
5. 25x2
6. 50x1








